# Generated by Django 5.0.2 on 2024-03-25 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Project_name', models.CharField(max_length=1000)),
                ('Project_Date', models.DateField()),
                ('Project_Type', models.CharField(choices=[('WEB DESIGN AND DEVELOPMENT', 'WEB DESIGN AND DEVELOPMENT'), ('BRANDING AND DESIGN IDENTITY', 'BRANDING AND DESIGN IDENTITY'), ('ADVERTISING AND MARKETING', 'ADVERTISING AND MARKETING'), ('CREATIVE CONSULTING', 'CREATIVE CONSULTING')], default='ADVERTISING AND MARKETING', max_length=30)),
                ('Client_Name', models.CharField(max_length=1000)),
                ('Author_Name', models.CharField(max_length=500)),
                ('Cover_image', models.FileField(null=True, upload_to='uploads/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'jpg', 'PNG', 'jpeg'])])),
                ('Image_1', models.ImageField(upload_to='uploads/')),
                ('Image_2', models.ImageField(upload_to='uploads/')),
                ('Image_3', models.ImageField(upload_to='uploads/')),
                ('Image_4', models.ImageField(upload_to='uploads/')),
                ('Image_5', models.ImageField(upload_to='uploads/')),
                ('Image_6', models.ImageField(upload_to='uploads/')),
                ('Image_7', models.ImageField(upload_to='uploads/')),
                ('Image_8', models.ImageField(upload_to='uploads/')),
                ('Project_Heading', models.CharField(max_length=1000)),
                ('Project_Description', models.CharField(max_length=3000)),
            ],
        ),
    ]
