# Generated by Django 5.0.2 on 2024-03-25 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flawsome_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Cover_image',
            field=models.FileField(null=True, upload_to='uploads/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'jpg', 'PNG', 'jpeg', 'GIF'])]),
        ),
    ]
