# Generated by Django 5.0.2 on 2024-03-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flawsome_web', '0002_alter_portfolio_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=254)),
                ('Service_Type', models.CharField(choices=[('NONE', 'NONE'), ('WEB DESIGN AND DEVELOPMENT', 'WEB DESIGN AND DEVELOPMENT'), ('BRANDING AND DESIGN IDENTITY', 'BRANDING AND DESIGN IDENTITY'), ('ADVERTISING AND MARKETING', 'ADVERTISING AND MARKETING'), ('CREATIVE CONSULTING', 'CREATIVE CONSULTING')], default='NONE', max_length=30)),
                ('Mobile_Number', models.CharField(max_length=1000)),
                ('Address', models.CharField(max_length=500)),
                ('Budget', models.CharField(max_length=500)),
                ('Project_Description', models.TextField(max_length=30000)),
            ],
        ),
    ]
