# Generated by Django 5.0.2 on 2024-03-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flawsome_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_Short_Description',
            field=models.CharField(max_length=3000),
        ),
    ]
